[classif-lstm]
'batch_size'= 5000
'glob_data_source'= '/training_defs/math*/*.xml.gz'
'TVT_split' = 0.8    ## Train  Validation Test split
'max_seq_len'= 400   # Length of padding and input of Embedding layer
'promath_dir'= 'promath' # name of dir with the processed arXiv tar files
#'save_path': 'glossary/test_lstm', #Path to save the positive results
'min_words'= 15 # min number of words for paragraphs to be considered

'model_type'= 'lstm'  # options are lstm or conv
'profiling'= false     # T/F whether to add the callback for profiling
'callbacks'= ['epoch_times',]

'lstm_cells' = 128 # Required LSTM layer parameter
'epochs' = 2
