# Where to find latexml in the local system
# The lines should be correct bash so can be sourced
# Always do config.toml for your local settings
[executables]
LATEXML_BIN="/usr/local/bin/latexml"
# Maximum time allowed for LaTeXML to run on a single file in seconds
MAXT=2400
[paths]
data="/mnt"
