compile_cache_dir: /home/luis/rm_me_estimator/rnn_example/cs_63fd9b1497032914e4be9a009cee51ddd21a94420c38c81e7697248b40467ffc
cs_info:
  cs_ip: null
  cs_target: ''
input_fn_handle: runny.py::input_fn
input_fn_params:
  description: FC-MNIST base model params
  model:
    activation_fn: relu
    dropout: 0.2
    hidden_sizes:
    - 500
    - 300
  optimizer:
    beta1: 0.9
    beta2: 0.999
    epsilon: 1.0e-08
    learning_rate: 0.001
  runconfig:
    compile_only: true
    cs_ip: null
    device: null
    eval_steps: null
    keep_checkpoint_max: 2
    max_steps: 100000
    mode: train
    model_dir: /home/luis/rm_me_estimator/rnn_example
    multireplica: false
    params: configs/params.yaml
    save_checkpoints_steps: 10000
    save_summary_steps: 500
    steps: null
    validate_only: false
  train_input:
    batch_size: 256
    data_dir: ./tfds
    num_parallel_calls: 0
    shuffle: true
logging: 40
mode: train
time_stop: 20
